#!/usr/bin/env python3
"""Module for building decision tree models using scikit-learn"""
from sklearn import metrics


def evaluate(true_labels, predicted_labels, class_names):
    """generates a detailed classification report using Scikit-learn.
    
    Args:
        true_labels: Ground truth labels
        predicted_labels: Predicted labels
        class_names: List of class names corresponding to the label indices

    Returns:
        A string containing the classification report generated by Scikit-learn.
    """
    """ # previous attempts, single versions
    metrics.precision_score(true_labels, predicted_labels)
    metrics.recall_score(true_labels, predicted_labels)
    metrics.f1_score(true_labels, predicted_labels)
    metrics.support
    """
    return metrics.classification_report(true_labels, predicted_labels, target_names=class_names)