#!/usr/bin/env python3
"""Module for building decision tree models using scikit-learn"""
from sklearn import model_selection


def prepruning(X, y, clf):
    """ uses Scikit-learn to perform a Grid Search for the best pre-pruning hyperparameters 
    for a decision tree classifier.
    
    Args:
        X: Input features
        y: Target labels
        clf: An untrained DecisionTreeClassifier instance

    Returns:
        A string containing the classification report generated by Scikit-learn.
    """
    my_param_grid = {"criterion": "gini",
                  "max_depth": [2, 3, 4, 5]
                  "min_samples_leaf": [2, 3, 4, 5]
                  "min_samples_split": [2, 3, 4, 5]
                  }
    model_selection.GridSearchCV(clf, param_grid=my_param_grid)
    clf.fit(X, y)
    return 